name: Unpack zips to repo

on:
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  unpack:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install unzip
        run: |
          sudo apt-get update
          sudo apt-get install -y unzip

      - name: Unzip code pack if present
        run: |
          if [ -f "4t_hotfix_pack.zip" ]; then
            echo "Found 4t_hotfix_pack.zip -> unzipping to repo root"
            unzip -o 4t_hotfix_pack.zip -d .
          else
            echo "No 4t_hotfix_pack.zip in repo root"
          fi

      - name: Unzip data pack if present
        run: |
          mkdir -p data
          if [ -f "ETHUSDT_1min_2020_2025.zip" ]; then
            echo "Found ETHUSDT_1min_2020_2025.zip -> unzipping to data/"
            unzip -o ETHUSDT_1min_2020_2025.zip -d data
          else
            echo "No ETHUSDT_1min_2020_2025.zip in repo root"
          fi
          ls -lh data || true

      - name: Commit unpacked files
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Unpack code/data zips into repo" || echo "Nothing to commit"
          git push
