name: "Backtest Guard Sweep V1.1 — G2b Baseline + 7 Runs (SHA pinned)"

on:
  workflow_dispatch:
    inputs:
      CODE_ZIP:
        description: "Code ZIP path (repo-relative or URL)"
        required: true
        default: "trade_v1.1.3.1.zip"
      DATA_ZIP:
        description: "Data ZIP path (repo-relative or URL)"
        required: true
        default: "ETHUSDT_1min_2020_2025.zip"
      CSV_GLOB:
        description: "Glob inside data zip (e.g., **/*ETHUSDT*1m*202*.csv)"
        required: true
        default: "**/*ETHUSDT*1m*202*.csv"

jobs:
  backtest:
    runs-on: ubuntu-latest
    timeout-minutes: 70
    strategy:
      fail-fast: false
      matrix:
        include:
          # --- Exit 강화(3) ---
          - id: E1_be_only
            TP_PCT: 0.010
            SL_PCT: 0.005
            COVERAGE_TARGET: 5
            TEMP: 1.7
            HOLD_BARS: 30
            FEES_BPS_PER_LEG: 0
            SLIPPAGE_BPS: 0
            BE_ON: true
            BE_TRIGGER_PCT: 0.003   # +0.30%에서 BE
            TRAIL_ON: false
            TRAIL_START_PCT: 0.005  # +0.50%부터 트레일
            TRAIL_GAP_PCT: 0.0025   # 0.25% 트레일 간격
          - id: E2_trail_only
            TP_PCT: 0.010
            SL_PCT: 0.005
            COVERAGE_TARGET: 5
            TEMP: 1.7
            HOLD_BARS: 30
            FEES_BPS_PER_LEG: 0
            SLIPPAGE_BPS: 0
            BE_ON: false
            BE_TRIGGER_PCT: 0.003
            TRAIL_ON: true
            TRAIL_START_PCT: 0.005
            TRAIL_GAP_PCT: 0.0025
          - id: E3_be_and_trail
            TP_PCT: 0.010
            SL_PCT: 0.005
            COVERAGE_TARGET: 5
            TEMP: 1.7
            HOLD_BARS: 30
            FEES_BPS_PER_LEG: 0
            SLIPPAGE_BPS: 0
            BE_ON: true
            BE_TRIGGER_PCT: 0.003
            TRAIL_ON: true
            TRAIL_START_PCT: 0.005
            TRAIL_GAP_PCT: 0.0025

          # --- Gate 미세조정(2) ---
          - id: GATE1_cov3
            TP_PCT: 0.010
            SL_PCT: 0.005
            COVERAGE_TARGET: 3
            TEMP: 1.7
            HOLD_BARS: 30
            FEES_BPS_PER_LEG: 0
            SLIPPAGE_BPS: 0
            BE_ON: false
            BE_TRIGGER_PCT: 0.003
            TRAIL_ON: false
            TRAIL_START_PCT: 0.005
            TRAIL_GAP_PCT: 0.0025
          - id: GATE2_cov7
            TP_PCT: 0.010
            SL_PCT: 0.005
            COVERAGE_TARGET: 7
            TEMP: 1.7
            HOLD_BARS: 30
            FEES_BPS_PER_LEG: 0
            SLIPPAGE_BPS: 0
            BE_ON: false
            BE_TRIGGER_PCT: 0.003
            TRAIL_ON: false
            TRAIL_START_PCT: 0.005
            TRAIL_GAP_PCT: 0.0025

          # --- 비용 스트레스(2) ---
          - id: COST1_fee5
            TP_PCT: 0.010
            SL_PCT: 0.005
            COVERAGE_TARGET: 5
            TEMP: 1.7
            HOLD_BARS: 30
            FEES_BPS_PER_LEG: 5
            SLIPPAGE_BPS: 0
            BE_ON: false
            BE_TRIGGER_PCT: 0.003
            TRAIL_ON: false
            TRAIL_START_PCT: 0.005
            TRAIL_GAP_PCT: 0.0025
          - id: COST2_fee5_slip10
            TP_PCT: 0.010
            SL_PCT: 0.005
            COVERAGE_TARGET: 5
            TEMP: 1.7
            HOLD_BARS: 30
            FEES_BPS_PER_LEG: 5
            SLIPPAGE_BPS: 10
            BE_ON: false
            BE_TRIGGER_PCT: 0.003
            TRAIL_ON: false
            TRAIL_START_PCT: 0.005
            TRAIL_GAP_PCT: 0.0025

    env:
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "1"

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Python 3.11
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: "3.11"

      - name: Init workspace
        run: |
          set -euo pipefail
          rm -rf tmp _out_4u scripts
          mkdir -p tmp/trade tmp/data tmp/raw _out_4u/run _out_4u/logs scripts
          : > _out_4u/logs/stdout.log

      - name: Bring zips
        run: |
          set -euo pipefail
          CODE_ZIP="${{ github.event.inputs.CODE_ZIP }}"
          DATA_ZIP="${{ github.event.inputs.DATA_ZIP }}"
          fetch() { src="$1"; dst="$2"; if echo "$src" | grep -qiE '^https?://'; then curl -L "$src" -o "$dst"; else cp -f "$src" "$dst"; fi; }
          fetch "$CODE_ZIP" tmp/code.zip
          fetch "$DATA_ZIP" tmp/data.zip
          ls -l tmp/*.zip

      - name: Unzip packs
        run: |
          set -euo pipefail
          unzip -oq tmp/code.zip -d tmp/raw
          if [ "$(find tmp/raw -mindepth 1 -maxdepth 1 -type d | wc -l)" -eq 1 ] &&              [ "$(find tmp/raw -mindepth 1 -maxdepth 1 -type f | wc -l)" -eq 0 ]; then
            mv tmp/raw/*/* tmp/trade/ 2>/dev/null || mv tmp/raw/* tmp/trade/
          else
            mv tmp/raw/* tmp/trade/ 2>/dev/null || true
          fi
          unzip -oq tmp/data.zip -d tmp/data

      - name: Python deps
        working-directory: tmp/trade
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt || true; fi
          pip install --no-cache-dir numpy pandas pyyaml scikit-learn || true

      - name: Write helpers (apply_config_patch.py & entrypoint_run.sh)
        shell: bash
        run: |
          set -Eeuo pipefail
          mkdir -p scripts
          cat > scripts/apply_config_patch.py <<'PY'
          import os, yaml
          from pathlib import Path
          base = Path("tmp/trade/conf/config.yml")
          eff  = Path("tmp/trade/conf/config.effective.yml")
          cfg = {}
          if base.exists():
              cfg = yaml.safe_load(base.read_text()) or {}
          for k in ("pricing","trading","gating","calibration","trade","gate","costs"):
              cfg.setdefault(k, {})
          tp=float(os.getenv("TP_PCT","0.010"))
          sl=float(os.getenv("SL_PCT","0.005"))
          cov=float(os.getenv("COVERAGE_TARGET","5"))
          temp=float(os.getenv("TEMP","1.7"))
          fees=float(os.getenv("FEES_BPS_PER_LEG","0"))
          slip=float(os.getenv("SLIPPAGE_BPS","0"))
          hold=int(float(os.getenv("HOLD_BARS","30")))
          be_on=os.getenv("BE_ON","false").lower()=="true"
          be_tr=float(os.getenv("BE_TRIGGER_PCT","0.003"))
          tr_on=os.getenv("TRAIL_ON","false").lower()=="true"
          tr_st=float(os.getenv("TRAIL_START_PCT","0.005"))
          tr_gp=float(os.getenv("TRAIL_GAP_PCT","0.0025"))
          # write both new/legacy keys
          cfg["trading"]["tp_pct"]=tp; cfg["trading"]["sl_pct"]=sl
          cfg["trade"]["tp_pct"]=tp;   cfg["trade"]["sl_pct"]=sl
          cfg["trade"]["hold_bars"]=hold
          cfg["trade"]["be_on"]=be_on
          cfg["trade"]["be_trigger_pct"]=be_tr
          cfg["trade"]["trail_on"]=tr_on
          cfg["trade"]["trail_start_pct"]=tr_st
          cfg["trade"]["trail_gap_pct"]=tr_gp
          cfg["gating"]["coverage_target"]=cov
          cfg["calibration"]["temperature"]=temp
          cfg["gate"]["temp"]=temp
          # fees
          psec = cfg.setdefault("pricing", {})
          for key in ("fees_bps_per_leg","fee_bps_per_leg","per_leg_bps","fee_bps"):
              psec[key] = fees
          csec = cfg.setdefault("costs", {})
          csec["taker_bps"] = fees
          csec["slippage_bps"] = slip
          eff.parent.mkdir(parents=True, exist_ok=True)
          eff.write_text(yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True))
          print("WROTE", eff)
          PY
          cat > scripts/entrypoint_run.sh <<'BASH'
          #!/usr/bin/env bash
          set -Eeuo pipefail
          export PYTHONPATH="tmp/trade:tmp/trade/backtest:${PYTHONPATH:-}"
          SEL=$(python - <<'PY'
          import glob,os
          pat=os.environ.get("CSV_ROOT","tmp/data")+"/"+os.environ.get("CSV_GLOB","**/*.csv")
          paths=sorted(glob.glob(pat, recursive=True))
          if not paths:
              paths=sorted(glob.glob("tmp/data/**/*.csv", recursive=True))
          print(paths[0] if paths else "")
          PY
          )
          echo "$SEL" > scripts/CSV_PATH.txt
          [ -n "$SEL" ] && [ -f "$SEL" ] || { echo "::error::No CSV matched. Check CSV_GLOB."; exit 3; }
          python -u scripts/apply_config_patch.py
          cp -f tmp/trade/conf/config.effective.yml tmp/trade/conf/config.yml || true
          # pre-write used_config for traceability
          python - <<'PY'
          from pathlib import Path
          try:
            from backtest.loader_sot import load_effective_config
            load_effective_config()
          except Exception as e:
            print("WARN: failed to pre-write used_config:", e)
          PY
          if [ -f tmp/trade/run_4u.py ]; then
            python -u tmp/trade/run_4u.py --data_path "$(cat scripts/CSV_PATH.txt)" --config tmp/trade/conf/config.yml 2>&1 | tee -a _out_4u/logs/stdout.log || true
          elif [ -f backtest/runner.py ]; then
            python -u backtest/runner.py 2>&1 | tee -a _out_4u/logs/stdout.log || true
          else
            echo "::error::No runner found"; exit 1
          fi
          mkdir -p _out_4u/run
          for f in summary.json preds_test.csv trades.csv gating_debug.json used_config.json; do
            [ -f "_out_4u/run/$f" ] || : > "_out_4u/run/$f"
          done
          BASH
          chmod +x scripts/entrypoint_run.sh

      - name: Resolve CSV path (robust)
        env:
          CSV_GLOB: ${{ github.event.inputs.CSV_GLOB }}
        run: |
          set -euo pipefail
          python - <<'PY'
          import os, glob, json
          root="tmp/data"
          pat=os.environ.get("CSV_GLOB") or "**/*.csv"
          cands=sorted(glob.glob(os.path.join(root, pat), recursive=True))
          if not cands:
              cands=sorted(glob.glob(os.path.join(root, "**/*.csv"), recursive=True))
          sel=cands[0] if cands else ""
          open("scripts/CSV_PATH.txt","w").write(sel)
          print({"selected": sel, "count": len(cands)})
          if not sel:
              raise SystemExit("NO_CSV_FOUND")
          PY
          echo "CSV_PATH=$(cat scripts/CSV_PATH.txt)"

      - name: Build effective config (pre-run)
        env:
          TP_PCT: ${{ matrix.TP_PCT }}
          SL_PCT: ${{ matrix.SL_PCT }}
          COVERAGE_TARGET: ${{ matrix.COVERAGE_TARGET }}
          TEMP: ${{ matrix.TEMP }}
          FEES_BPS_PER_LEG: ${{ matrix.FEES_BPS_PER_LEG }}
          SLIPPAGE_BPS: ${{ matrix.SLIPPAGE_BPS }}
          HOLD_BARS: ${{ matrix.HOLD_BARS }}
          BE_ON: ${{ matrix.BE_ON }}
          BE_TRIGGER_PCT: ${{ matrix.BE_TRIGGER_PCT }}
          TRAIL_ON: ${{ matrix.TRAIL_ON }}
          TRAIL_START_PCT: ${{ matrix.TRAIL_START_PCT }}
          TRAIL_GAP_PCT: ${{ matrix.TRAIL_GAP_PCT }}
        run: |
          set -euo pipefail
          mkdir -p tmp/trade/conf
          if [ ! -f tmp/trade/conf/config.yml ]; then
            python -c "import yaml,pathlib; p=pathlib.Path('tmp/trade/conf/config.yml'); cfg={'pricing':{},'trading':{},'gating':{},'calibration':{},'trade':{},'gate':{},'costs':{}}; p.parent.mkdir(parents=True, exist_ok=True); p.write_text(yaml.safe_dump(cfg, sort_keys=False, allow_unicode=True)); print('WROTE base config:', p)"
          fi
          python -u scripts/apply_config_patch.py
          test -f tmp/trade/conf/config.effective.yml || { echo '::error::Failed to produce config.effective.yml'; exit 2; }
          echo '--- effective head ---'
          sed -n '1,200p' tmp/trade/conf/config.effective.yml || true

      - name: Assert effective config matches inputs (pre-run)
        env:
          TP_PCT: ${{ matrix.TP_PCT }}
          SL_PCT: ${{ matrix.SL_PCT }}
          COVERAGE_TARGET: ${{ matrix.COVERAGE_TARGET }}
          TEMP: ${{ matrix.TEMP }}
          FEES_BPS_PER_LEG: ${{ matrix.FEES_BPS_PER_LEG }}
          SLIPPAGE_BPS: ${{ matrix.SLIPPAGE_BPS }}
          HOLD_BARS: ${{ matrix.HOLD_BARS }}
          BE_ON: ${{ matrix.BE_ON }}
          BE_TRIGGER_PCT: ${{ matrix.BE_TRIGGER_PCT }}
          TRAIL_ON: ${{ matrix.TRAIL_ON }}
          TRAIL_START_PCT: ${{ matrix.TRAIL_START_PCT }}
          TRAIL_GAP_PCT: ${{ matrix.TRAIL_GAP_PCT }}
        run: |
          set -euo pipefail
          python - <<'PY'
          import os, yaml, math
          cfg = yaml.safe_load(open("tmp/trade/conf/config.effective.yml")) or {}
          def get(d, path):
              for k in path.split('.'):
                  if not isinstance(d, dict): return None
                  d = d.get(k)
              return d
          def fee_total(c):
              taker = float(get(c,"costs.taker_bps") or 0.0)
              slip  = float(get(c,"costs.slippage_bps") or 0.0)
              for k in ("pricing.fees_bps_per_leg","pricing.fee_bps_per_leg","pricing.per_leg_bps","pricing.fee_bps"):
                  v = get(c,k)
                  if v is not None: taker = float(v); break
              return taker + slip
          exp = {
            "tp": float(os.getenv("TP_PCT")),
            "sl": float(os.getenv("SL_PCT")),
            "cov": float(os.getenv("COVERAGE_TARGET")),
            "temp": float(os.getenv("TEMP")),
            "fee": float(os.getenv("FEES_BPS_PER_LEG")) + float(os.getenv("SLIPPAGE_BPS")),
            "hold": float(os.getenv("HOLD_BARS")),
            "be_on": os.getenv("BE_ON","false").lower()=="true",
            "be_tr": float(os.getenv("BE_TRIGGER_PCT")),
            "tr_on": os.getenv("TRAIL_ON","false").lower()=="true",
            "tr_st": float(os.getenv("TRAIL_START_PCT")),
            "tr_gp": float(os.getenv("TRAIL_GAP_PCT")),
          }
          eff = {
            "tp": float(get(cfg,"trade.tp_pct") or get(cfg,"trading.tp_pct") or -1),
            "sl": float(get(cfg,"trade.sl_pct") or get(cfg,"trading.sl_pct") or -1),
            "cov": float(get(cfg,"gating.coverage_target") or -1),
            "temp": float(get(cfg,"gate.temp") or get(cfg,"calibration.temperature") or -1),
            "fee": float(fee_total(cfg)),
            "hold": float(get(cfg,"trade.hold_bars") or -1),
            "be_on": bool(get(cfg,"trade.be_on")),
            "be_tr": float(get(cfg,"trade.be_trigger_pct") or -1),
            "tr_on": bool(get(cfg,"trade.trail_on")),
            "tr_st": float(get(cfg,"trade.trail_start_pct") or -1),
            "tr_gp": float(get(cfg,"trade.trail_gap_pct") or -1),
          }
          print("EXPECTED:", exp); print("EFFECTIVE:", eff)
          for k in eff:
            if eff[k] != exp[k]:
              raise SystemExit(f"PARAM_MISMATCH:{k}:{eff[k]}!={exp[k]}")
          PY

      - name: Run backtest (with patch)
        env:
          CSV_GLOB: ${{ github.event.inputs.CSV_GLOB }}
          TP_PCT: ${{ matrix.TP_PCT }}
          SL_PCT: ${{ matrix.SL_PCT }}
          COVERAGE_TARGET: ${{ matrix.COVERAGE_TARGET }}
          TEMP: ${{ matrix.TEMP }}
          FEES_BPS_PER_LEG: ${{ matrix.FEES_BPS_PER_LEG }}
          SLIPPAGE_BPS: ${{ matrix.SLIPPAGE_BPS }}
          HOLD_BARS: ${{ matrix.HOLD_BARS }}
          BE_ON: ${{ matrix.BE_ON }}
          BE_TRIGGER_PCT: ${{ matrix.BE_TRIGGER_PCT }}
          TRAIL_ON: ${{ matrix.TRAIL_ON }}
          TRAIL_START_PCT: ${{ matrix.TRAIL_START_PCT }}
          TRAIL_GAP_PCT: ${{ matrix.TRAIL_GAP_PCT }}
        run: |
          set -Eeuo pipefail
          ( bash -x scripts/entrypoint_run.sh ) 2>&1 | tee -a _out_4u/logs/stdout.log || true

      - name: Upload artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: backtest_sweep_${{ matrix.id }}
          path: |
            _out_4u/**
            tmp/trade/conf/config.effective.yml
            scripts/CSV_PATH.txt
