name: Backtest-Grid-Stage3
on:
  workflow_dispatch:
    inputs:
      CODE_ZIP:
        description: 'Path or URL to code zip (repo root file name allowed)'
        required: true
        default: strategy_v1_codepack_v1.0.zip
      DATA_ZIP:
        description: 'Path or URL to data zip (repo root file name allowed)'
        required: true
        default: ETHUSDT_1min_2020_2025.zip
      CSV_GLOB:
        description: 'CSV glob (e.g. **/*ETHUSDT*1min*2020*2025*.csv)'
        required: false
        default: "**/*ETHUSDT*1min*2020*2025*.csv"
jobs:
  grid:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        thr: [-0.1, 0.0, 0.1]
        a: [1.0, 1.2]
        hold: [6, 8]
    steps:
      - name: Install deps
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip || true
          pip install pandas numpy pyyaml || true

      - name: Acquire code/data (local / URL / repo raw)
        env:
          CODE_ZIP: "${{ github.event.inputs.CODE_ZIP }}"
          DATA_ZIP: "${{ github.event.inputs.DATA_ZIP }}"
        run: |
          set -euo pipefail
          mkdir -p tmp/trade tmp/data _out_4u/run
          # CODE_ZIP
          CSRC=""
          if [ -f "$CODE_ZIP" ]; then
            CSRC="$CODE_ZIP"
          elif echo "$CODE_ZIP" | grep -qiE '^https?://'; then
            echo "Downloading code from URL: $CODE_ZIP"
            curl -fL "$CODE_ZIP" -o tmp/trade/code.zip
            CSRC="tmp/trade/code.zip"
          else
            RCODE="https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/$CODE_ZIP"
            echo "Trying repo raw URL: $RCODE"
            curl -fL "$RCODE" -o tmp/trade/code.zip
            CSRC="tmp/trade/code.zip"
          fi
          unzip -q "$CSRC" -d tmp/trade
          # DATA_ZIP
          DSRC=""
          if [ -f "$DATA_ZIP" ]; then
            DSRC="$DATA_ZIP"
          elif echo "$DATA_ZIP" | grep -qiE '^https?://'; then
            echo "Downloading data from URL: $DATA_ZIP"
            curl -fL "$DATA_ZIP" -o tmp/data/data.zip
            DSRC="tmp/data/data.zip"
          else
            RDATA="https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/$DATA_ZIP"
            echo "Trying repo raw URL: $RDATA"
            curl -fL "$RDATA" -o tmp/data/data.zip
            DSRC="tmp/data/data.zip"
          fi
          unzip -q "$DSRC" -d tmp/data

      - name: Patch params for this matrix
        env:
          THR: "${{ matrix.thr }}"
          AMP: "${{ matrix.a }}"
          HOLD: "${{ matrix.hold }}"
        run: |
          set -euo pipefail
          PARAM=tmp/trade/conf/params.v1.yml
          sed -i -E "s/(^\s*thr:\s*).*/\1${{ env.THR }}/" "$PARAM"
          sed -i -E "s/(^\s*a:\s*).*/\1${{ env.AMP }}/" "$PARAM"
          sed -i -E "s/(^hold:\s*).*/hold: ${{ env.HOLD }}/" "$PARAM"
          echo "---- params.v1.yml ----"
          cat "$PARAM"

      - name: Preflight strict
        run: |
          set -euo pipefail
          python tmp/trade/preflight_strict.py --data-root tmp/data --csv-glob "${{ github.event.inputs.CSV_GLOB }}" --outdir _out_4u/run

      - name: Detect entrypoint and run
        env:
          CSV_GLOB: "${{ github.event.inputs.CSV_GLOB }}"
        run: |
          set -euo pipefail
          ENTRY=""
          for c in "tmp/trade/run_4u.py" "tmp/trade/backtest/run_4u.py" "tmp/trade/run.py" "tmp/trade/backtest/runner.py"; do
            if [ -f "$c" ]; then ENTRY="$c"; break; fi
          done
          if [ -z "$ENTRY" ]; then echo "No entrypoint found"; exit 1; fi
          echo "ENTRY=$ENTRY"
          python "$ENTRY" --data-root tmp/data --csv-glob "$CSV_GLOB" --outdir _out_4u/run || true
          python - <<'PY'
import pandas as pd, json, numpy as np, os
p='_out_4u/run/preds_test.csv'
m={'winrate':None,'mcc':None}
if os.path.exists(p):
    df=pd.read_csv(p)
    # label = next-bar close direction using 'score' as proxy if price not present
    ret=df['score'].shift(-1).fillna(0.0).to_numpy()
    y_true=np.sign(ret); y_true[y_true==0]=1
    y_pred=np.where(df['signal'].to_numpy()>=0,1,-1)
    tp=int(np.sum((y_true==1)&(y_pred==1)))
    tn=int(np.sum((y_true==-1)&(y_pred==-1)))
    fp=int(np.sum((y_true==-1)&(y_pred==1)))
    fn=int(np.sum((y_true==1)&(y_pred==-1)))
    winrate=float((tp+tn)/max(1,len(df)))
    num=tp*tn-fp*fn; den=((tp+fp)*(tp+fn)*(tn+fp)*(tn+fn))**0.5+1e-9
    m['winrate']=winrate; m['mcc']=float(num/den)
with open('_out_4u/run/grid_metrics.json','w') as f: json.dump(m,f,indent=2)
PY

      - name: Upload artifacts
        uses: actions/upload-artifact@84480863f228bb9747b473957fcc9e309aa96097
        with:
          name: "grid-thr=${{ matrix.thr }}-a=${{ matrix.a }}-hold=${{ matrix.hold }}"
          path: |
            _out_4u/run/gating_debug.json
            _out_4u/run/summary.json
            _out_4u/run/preds_test.csv
            _out_4u/run/trades.csv
            _out_4u/run/grid_metrics.json
