
name: Backtest-Grid-V2
on:
  workflow_dispatch:
    inputs:
      CODE_ZIP:
        description: 'Path or URL to V2 code zip (repo root file name allowed)'
        required: true
        default: strategy_v2_codepack_v2.0.1.zip
      DATA_ZIP:
        description: 'Path or URL to data zip (repo root file name allowed)'
        required: true
        default: ETHUSDT_1min_2020_2025.zip
      CSV_GLOB:
        description: 'CSV glob (e.g. **/*ETHUSDT*1min*2020*2025*.csv)'
        required: false
        default: "**/*ETHUSDT*1min*2020*2025*.csv"
      P_THR_RANGE:
        description: 'entry.p_thr.range constant (matrix covers trend only)'
        required: false
        default: "0.55"
      SL_ATR:
        description: 'exit.sl_atr constant (matrix covers tp_atr only)'
        required: false
        default: "0.5"

jobs:
  grid:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ofi_thr: [0.15, 0.20, 0.25]
        pthr_tr: [0.55, 0.60]
        tp_atr: [0.70, 0.90]
    steps:
      - name: Install deps (pandas, numpy, pyyaml, numba)
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip || true
          pip install pandas numpy pyyaml numba || true

      - name: Acquire code/data (local / URL / repo raw)
        env:
          CODE_ZIP: "${{ github.event.inputs.CODE_ZIP }}"
          DATA_ZIP: "${{ github.event.inputs.DATA_ZIP }}"
        run: |
          set -euo pipefail
          mkdir -p tmp/trade tmp/data _out_4u/run tools
          # CODE_ZIP
          if [ -f "$CODE_ZIP" ]; then CSRC="$CODE_ZIP";           elif echo "$CODE_ZIP" | grep -qiE '^https?://'; then curl -fL "$CODE_ZIP" -o tmp/trade/code.zip; CSRC="tmp/trade/code.zip";           else RCODE="https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/$CODE_ZIP"; curl -fL "$RCODE" -o tmp/trade/code.zip; CSRC="tmp/trade/code.zip"; fi
          unzip -q "$CSRC" -d tmp/trade
          # DATA_ZIP
          if [ -f "$DATA_ZIP" ]; then DSRC="$DATA_ZIP";           elif echo "$DATA_ZIP" | grep -qiE '^https?://'; then curl -fL "$DATA_ZIP" -o tmp/data/data.zip; DSRC="tmp/data/data.zip";           else RDATA="https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/$DATA_ZIP"; curl -fL "$RDATA" -o tmp/data/data.zip; DSRC="tmp/data/data.zip"; fi
          unzip -q "$DSRC" -d tmp/data
          # guard for namespace packages
          touch tmp/trade/strategy/__init__.py || true
          touch tmp/trade/strategy/v2/__init__.py || true

      - name: Patch params for this matrix (sed-free Python patch)
        env:
          OFI_THR: "${{ matrix.ofi_thr }}"
          P_THR_TR: "${{ matrix.pthr_tr }}"
          P_THR_RG: "${{ github.event.inputs.P_THR_RANGE }}"
          TP_ATR: "${{ matrix.tp_atr }}"
          SL_ATR: "${{ github.event.inputs.SL_ATR }}"
        run: |
          set -euo pipefail
          python - <<'PY'
import os, sys, yaml, json
path = 'tmp/trade/conf/params.v2.yml'
with open(path,'r') as f:
    cfg = yaml.safe_load(f)
cfg.setdefault('orderflow', {})
cfg.setdefault('entry', {}).setdefault('p_thr', {})
cfg.setdefault('exit', {})
def getf(k, dflt):
    try: return float(os.environ.get(k, dflt))
    except: return float(dflt)
cfg['orderflow']['ofi_thr'] = getf('OFI_THR', cfg['orderflow'].get('ofi_thr', 0.2))
cfg['entry']['p_thr']['trend'] = getf('P_THR_TR', cfg['entry']['p_thr'].get('trend', 0.6))
cfg['entry']['p_thr']['range'] = getf('P_THR_RG', cfg['entry']['p_thr'].get('range', 0.55))
cfg['exit']['tp_atr'] = getf('TP_ATR', cfg['exit'].get('tp_atr', 0.8))
cfg['exit']['sl_atr'] = getf('SL_ATR', cfg['exit'].get('sl_atr', 0.5))
with open(path,'w') as f:
    yaml.safe_dump(cfg, f, sort_keys=False)
print(json.dumps({'patched': path}))
PY

      - name: Preflight strict
        env:
          CSV_GLOB: "${{ github.event.inputs.CSV_GLOB }}"
        run: |
          set -euo pipefail
          python tmp/trade/preflight_strict.py --data-root tmp/data --csv-glob "$CSV_GLOB" --outdir _out_4u/run

      - name: Detect entrypoint and run (V2)
        env:
          CSV_GLOB: "${{ github.event.inputs.CSV_GLOB }}"
        run: |
          set -euo pipefail
          ENTRY=""
          for c in "tmp/trade/run_4u.py" "tmp/trade/backtest/run_4u.py" "tmp/trade/backtest/runner.py"; do
            if [ -f "$c" ]; then ENTRY="$c"; break; fi
          done
          if [ -z "$ENTRY" ]; then echo "No entrypoint found"; exit 1; fi
          echo "ENTRY=$ENTRY"
          python "$ENTRY" --data-root tmp/data --csv-glob "$CSV_GLOB" --outdir _out_4u/run --params tmp/trade/conf/params.v2.yml

      - name: Grid metrics
        run: |
          set -euo pipefail
          python - <<'PY'
import json, os
s = json.load(open('_out_4u/run/summary.json')) if os.path.exists('_out_4u/run/summary.json') else {}
m = {'cum_pnl_close_based': s.get('cum_pnl_close_based', None),
     'avg_gatep': s.get('avg_gatep', None),
     'trend_frac': s.get('trend_frac', None),
     'range_frac': s.get('range_frac', None)}
json.dump(m, open('_out_4u/run/grid_metrics.json','w'), indent=2)
PY

      - name: Upload artifacts
        uses: actions/upload-artifact@84480863f228bb9747b473957fcc9e309aa96097
        with:
          name: "v2-ofi=${{ matrix.ofi_thr }}-ptr=${{ matrix.pthr_tr }}-tp=${{ matrix.tp_atr }}"
          path: |
            _out_4u/run/gating_debug.json
            _out_4u/run/summary.json
            _out_4u/run/preds_test.csv
            _out_4u/run/trades.csv
            _out_4u/run/grid_metrics.json
