name: Compare Two Singles - force codepack runner
on:
  workflow_dispatch:

env:
  PYTHONUTF8: "1"
  PY_VERSION: "3.10"
  PARAMS_CHAMP: "conf/params_v2_champion.yml"
  PARAMS_ALT:   "conf/params.v2.yml"
  CSV_GLOB: "**/*ETHUSDT*1min*2020*2025*.csv"
  DATA_ZIP: "ETHUSDT_1min_2020_2025.zip"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (pinned)
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Setup Python (pinned)
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: ${{ env.PY_VERSION }}

      - name: Deps
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip wheel setuptools
          pip install "numpy==1.26.4" "pandas==2.2.2" "numba==0.59.1" "llvmlite==0.42.0" "pyyaml"

      - name: Unzip data if present
        run: |
          set -euo pipefail
          if [ -f "${DATA_ZIP}" ]; then unzip -o "${DATA_ZIP}" >/dev/null; fi

      - name: Normalize CSV_GLOB to repo root
        run: |
          set -euo pipefail
          ROOTF="$(basename "$GITHUB_WORKSPACE")"
          CSVG="${CSV_GLOB#${ROOTF}/}"; CSVG="${CSVG#./}"
          echo "CSVG_SANITIZED=$CSVG" >> "$GITHUB_ENV"

      - name: Export PYTHONPATH
        run: echo "PYTHONPATH=." >> $GITHUB_ENV

      - name: Sanity check
        run: |
          set -euo pipefail
          test -f ci/wfo_entry.py || { echo "ci/wfo_entry.py missing"; exit 2; }
          test -f "${PARAMS_CHAMP}" || { echo "PARAMS_CHAMP not found"; exit 2; }
          test -f "${PARAMS_ALT}"   || { echo "PARAMS_ALT not found"; exit 2; }
          test -f "strategy_v2_codepack_v2.1.3.zip" || { echo "codepack zip missing"; exit 2; }

      - name: Use runner from codepack (force)
        run: |
          set -euo pipefail
          rm -rf _codepack
          unzip -o strategy_v2_codepack_v2.1.3.zip -d _codepack >/dev/null
          echo "RUNNER_PATH_EXP=_codepack/backtest/runner.py" >> $GITHUB_ENV
          test -f _codepack/backtest/runner.py || { echo "runner not found"; exit 2; }

      - name: Run SINGLE - Champion
        run: |
          set -euo pipefail
          OUT="out_single_champion"
          python ci/wfo_entry.py --params "${PARAMS_CHAMP}" --data-root "." --csv-glob "$CSVG_SANITIZED" --runner "$RUNNER_PATH_EXP" --outdir "$OUT"
          ( cd "$OUT" && zip -rq ../bundle_single_champion.zip . )

      - name: Run SINGLE - Alt
        run: |
          set -euo pipefail
          OUT="out_single_alt"
          python ci/wfo_entry.py --params "${PARAMS_ALT}" --data-root "." --csv-glob "$CSVG_SANITIZED" --runner "$RUNNER_PATH_EXP" --outdir "$OUT"
          ( cd "$OUT" && zip -rq ../bundle_single_alt.zip . )

      - name: Upload artifacts (pinned)
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: singles_compare
          path: |
            bundle_single_champion.zip
            bundle_single_alt.zip