name: Compare Two Singles (Champion vs Alt) v2

on:
  workflow_dispatch:
    inputs:
      PARAMS_CHAMP:
        default: "conf/params_champion.yml"
      PARAMS_ALT:
        default: "conf/params_alt.yml"
      CSV_GLOB:
        # 루트 기준! 여기엔 레포명(폴더명) 넣지 마세요.
        default: "**/*ETHUSDT*1min*2020*2025*.csv"
      DATA_ZIP:
        # 루트에 올려둔 데이터 ZIP 파일명 (있으면 자동 언집)
        default: "ETHUSDT_1min_2020_2025.zip"
      RUNNER_PATH:
        default: ""
      PY_VERSION:
        default: "3.10"

env:
  PYTHONUTF8: "1"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (pinned)
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8

      - name: Setup Python (pinned)
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with: { python-version: ${{ github.event.inputs.PY_VERSION }} }

      - name: Deps (numba 호환 고정)
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip wheel setuptools
          pip install "numpy==1.26.4" "pandas==2.2.2" "numba==0.59.1" "llvmlite==0.42.0" "pyyaml"

      - name: Unzip data (optional)
        run: |
          set -euo pipefail
          ZIP="${{ github.event.inputs.DATA_ZIP }}"
          if [ -n "$ZIP" ] && [ -f "$ZIP" ]; then
            echo "[data] unzip $ZIP"
            unzip -o "$ZIP" >/dev/null
          else
            echo "[data] no zip to extract (skip)"
          fi
          echo "[data] show top-level files:"; ls -al | sed -n '1,120p'

      - name: Export PYTHONPATH
        run: echo "PYTHONPATH=.:${GITHUB_WORKSPACE}/src" >> $GITHUB_ENV

      - name: Sanity check (scripts & params)
        run: |
          set -euo pipefail
          test -f ci/wfo_entry.py || { echo "ci/wfo_entry.py missing"; exit 2; }
          test -f "${{ github.event.inputs.PARAMS_CHAMP }}" || { echo "PARAMS_CHAMP not found"; exit 2; }
          test -f "${{ github.event.inputs.PARAMS_ALT }}"   || { echo "PARAMS_ALT not found"; exit 2; }

      - name: Run SINGLE — Champion
        env:
          RUNNER: ${{ github.event.inputs.RUNNER_PATH }}
          CSVG:   ${{ github.event.inputs.CSV_GLOB }}
          PF:     ${{ github.event.inputs.PARAMS_CHAMP }}
        run: |
          set -euo pipefail
          OUT="out_single_champion"
          # data-root는 반드시 루트(.) — 레포명 포함 금지
          python ci/wfo_entry.py --params "$PF" --data-root "." --csv-glob "$CSVG" --runner "$RUNNER" --outdir "$OUT"
          ( cd "$OUT" && zip -rq ../bundle_single_champion.zip . )

      - name: Run SINGLE — Alt(≈3.75)
        env:
          RUNNER: ${{ github.event.inputs.RUNNER_PATH }}
          CSVG:   ${{ github.event.inputs.CSV_GLOB }}
          PF:     ${{ github.event.inputs.PARAMS_ALT }}
        run: |
          set -euo pipefail
          OUT="out_single_alt"
          python ci/wfo_entry.py --params "$PF" --data-root "." --csv-glob "$CSVG" --runner "$RUNNER" --outdir "$OUT"
          ( cd "$OUT" && zip -rq ../bundle_single_alt.zip . )

      - name: Upload artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: singles_compare
          path: |
            bundle_single_champion.zip
            bundle_single_alt.zip
