name: Precheck-STRICT-NO-CHECKOUT
on:
  workflow_dispatch:
    inputs:
      DATA_ZIP:
        description: 'Path or URL to data zip (repo root file name allowed)'
        required: true
        default: ETHUSDT_1min_2020_2025.zip
      CSV_GLOB:
        description: 'CSV glob (e.g. **/*ETHUSDT*1min*2020*2025*.csv)'
        required: false
        default: "**/*ETHUSDT*1min*2020*2025*.csv"
jobs:
  precheck:
    runs-on: ubuntu-latest
    steps:
      - name: Install Python deps
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip || true
          pip install pandas numpy pyyaml || true

      - name: Acquire data zip (local / URL / repo raw)
        env:
          DATA_ZIP: "${{ github.event.inputs.DATA_ZIP }}"
        run: |
          set -euo pipefail
          mkdir -p tmp/data _out_4u/run tools
          SRC=""
          if [ -f "$DATA_ZIP" ]; then
            SRC="$DATA_ZIP"
          elif echo "$DATA_ZIP" | grep -qiE '^https?://'; then
            echo "Downloading DATA_ZIP from URL: $DATA_ZIP"
            curl -fL "$DATA_ZIP" -o tmp/data/data.zip
            SRC="tmp/data/data.zip"
          else
            RAW="https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/$DATA_ZIP"
            echo "Trying repo raw URL: $RAW"
            curl -fL "$RAW" -o tmp/data/data.zip
            SRC="tmp/data/data.zip"
          fi
          unzip -q "$SRC" -d tmp/data

      - name: Acquire preflight_strict.py from repo raw
        run: |
          set -euo pipefail
          curl -fL "https://raw.githubusercontent.com/${{ github.repository }}/${{ github.ref_name }}/preflight_strict.py" -o tools/preflight_strict.py

      - name: Ensure artifacts exist
        run: |
          set -euo pipefail
          echo "{}" > _out_4u/run/gating_debug.json
          echo "{}" > _out_4u/run/summary.json
          echo "open_time,signal,score" > _out_4u/run/preds_test.csv
          echo "open_time,side,price,qty" > _out_4u/run/trades.csv

      - name: Run preflight
        run: |
          set -euo pipefail
          python tools/preflight_strict.py --data-root tmp/data --csv-glob "${{ github.event.inputs.CSV_GLOB }}" --outdir _out_4u/run

      - name: Upload artifacts
        uses: actions/upload-artifact@84480863f228bb9747b473957fcc9e309aa96097
        with:
          name: precheck-artifacts
          path: |
            _out_4u/run/gating_debug.json
            _out_4u/run/summary.json
            _out_4u/run/preds_test.csv
            _out_4u/run/trades.csv
