name: trade4v run (dispatch-only)
on:
  workflow_dispatch:
    inputs:
      data_csv:   { default: 'data/*.csv' }
      train_start:{ default: '2025-01-01 00:00:00' }
      train_end:  { default: '2025-04-30 23:59:00' }
      test_start: { default: '2025-05-01 00:00:00' }
      test_end:   { default: '2025-06-30 23:59:00' }
      H:          { default: '15' }
      fee_bps:    { default: '1.0' }
      slip_bps:   { default: '0.5' }
      k_day:      { default: '0:10,1:15,2:30' }
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab0f6f9c3f8b7497d1e5d00bbc
      - uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with: { python-version: '3.11' }
      - name: Deps
        run: |
          python -m pip install -q --upgrade pip
          pip install -q pandas pyarrow numpy scipy scikit-learn statsmodels
      - name: Unzip project
        run: |
          set -euo pipefail
          mkdir -p __extracted
          if ls *.zip 1>/dev/null 2>&1; then unzip -o -q "*.zip" -d __extracted || true; fi
          ROOT=""
          for d in __extracted/trade4v __extracted ./trade4v . ; do
            if [ -f "$d/trade4v/run_4u.py" ]; then ROOT="$d/trade4v"; break; fi
            if [ -f "$d/run_4u.py" ]; then ROOT="$d"; break; fi
          done
          rm -rf trade4v || true
          if [ -n "${ROOT}" ]; then
            [ -d "${ROOT}/trade4v" ] && { mkdir -p trade4v; shopt -s dotglob; mv "${ROOT}/trade4v"/* trade4v/; } || cp -r "${ROOT}" trade4v
          fi
          [ -d trade4v/trade4v ] && { shopt -s dotglob; mv trade4v/trade4v/* trade4v/; rmdir trade4v/trade4v; } || true
          test -f trade4v/run_4u.py || { echo "FATAL: run_4u.py missing"; exit 2; }
      - name: Prepare data
        id: prep
        run: |
          set -euo pipefail
          CSV_IN='${{ inputs.data_csv }}'
          if [[ "$CSV_IN" == *"*"* ]]; then CSV=$(ls -1 $CSV_IN 2>/dev/null | head -n1 || true); else CSV="$CSV_IN"; fi
          [ -f "$CSV" ] || { echo "FATAL: CSV not found"; exit 3; }
          python - "$CSV" <<'PY'