name: Scalper Backtest (ETH 1m)

on:
  workflow_dispatch:
  push:
    paths:
      - "eth_scalp_trader_pack_v0_1/**"
      - "ETHUSDT_1min_2020_2025.zip"
      - ".github/workflows/scalper_backtest.yml"

permissions:
  contents: read

jobs:
  backtest:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 1

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5.6.0
        with:
          python-version: "3.11"
          cache: pip

      - name: Show repo tree (debug)
        run: |
          set -euxo pipefail
          ls -al
          echo "------"
          if [ -f ETHUSDT_1min_2020_2025.zip ]; then echo "ETH zip present"; else echo "ETH zip MISSING!" && exit 2; fi
          if [ -f eth_scalp_trader_pack_v0_1.zip ]; then echo "Pack is zipped; please commit the folder, not zip." ; fi
          # 실제는 폴더로 커밋되어 있음(README 등). 트리만 출력
          tree -L 3 || true

      - name: Ensure pack layout & data folder
        run: |
          set -euxo pipefail
          test -d eth_scalp_trader_pack_v0_1 || { echo "eth_scalp_trader_pack_v0_1 폴더가 필요합니다."; exit 2; }
          mkdir -p eth_scalp_trader_pack_v0_1/data

      - name: Unzip ETH 1m data -> normalized filename
        run: |
          set -euxo pipefail
          workdir="$(pwd)"
          tmpdir="$(mktemp -d)"
          unzip -q "ETHUSDT_1min_2020_2025.zip" -d "$tmpdir"
          echo "Unzipped to: $tmpdir"
          # zip 내부에서 첫 번째 CSV를 탐지
          csv_src="$(find "$tmpdir" -type f -iname '*.csv' | head -n1 || true)"
          if [ -z "$csv_src" ]; then
            echo "CSV not found inside ETHUSDT_1min_2020_2025.zip"; ls -R "$tmpdir"; exit 3
          fi
          # 표준 경로/파일명으로 복사
          cp "$csv_src" "eth_scalp_trader_pack_v0_1/data/ETHUSDT-1m.csv"
          ls -al "eth_scalp_trader_pack_v0_1/data/"

      - name: Install requirements (pack-local)
        run: |
          set -euxo pipefail
          python -m pip install --upgrade pip
          pip install -r eth_scalp_trader_pack_v0_1/requirements.txt

      - name: Print config (debug)
        run: |
          set -euxo pipefail
          sed -n '1,160p' eth_scalp_trader_pack_v0_1/config.yml || true

      - name: Run backtest (cd into pack so config.yml is found)
        working-directory: eth_scalp_trader_pack_v0_1
        run: |
          set -euxo pipefail
          python run_backtest.py --config config.yml

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4.6.2
        with:
          name: backtest-results
          path: |
            eth_scalp_trader_pack_v0_1/**/results/**
            eth_scalp_trader_pack_v0_1/**/outputs/**
            eth_scalp_trader_pack_v0_1/**/equity*.csv
            eth_scalp_trader_pack_v0_1/**/metrics*.json
            eth_scalp_trader_pack_v0_1/logs/**
          if-no-files-found: warn
