name: backtest-scalper

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  backtest:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (pinned)
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332  # v4.1.7
        # ref: https://github.com/actions/checkout/releases/tag/v4.1.7

      - name: Setup Python 3.11 (pinned)
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
        with:
          python-version: "3.11"
          cache: "pip"
        # ref: https://github.com/actions/setup-python/releases/tag/v5.6.0

      - name: Show repository tree (debug)
        run: |
          pwd
          ls -la
          echo "---- zip files ----"
          ls -la *.zip || true

      - name: Unzip all packs to ./unzipped
        run: |
          set -euo pipefail
          mkdir -p unzipped
          shopt -s nullglob
          for z in *.zip; do
            echo "unzip $z -> unzipped/"
            unzip -q "$z" -d unzipped
          done

      - name: Place codepack at repo root as eth_scalp_trader_pack_v0_1
        run: |
          set -euo pipefail
          # 1) 이미 폴더가 있으면 유지
          if [ -d "eth_scalp_trader_pack_v0_1" ]; then
            echo "codepack already present: eth_scalp_trader_pack_v0_1"
          else
            # 2) unzip된 곳에서 codepack 폴더 찾기
            CANDIDATE="$(find unzipped -maxdepth 2 -type d -name 'eth_scalp_trader_pack_v0_1' | head -n1 || true)"
            if [ -n "${CANDIDATE:-}" ]; then
              mv "$CANDIDATE" ./eth_scalp_trader_pack_v0_1
            else
              echo "::error::eth_scalp_trader_pack_v0_1 폴더를 zip에서 찾지 못했습니다."
              echo "unzipped 내용:"
              find unzipped -maxdepth 3 -print
              exit 2
            fi
          fi
          echo "== codepack tree =="
          find eth_scalp_trader_pack_v0_1 -maxdepth 2 -print

      - name: Prepare data/ETHUSDT-1m.csv from uploaded ETH zip
        run: |
          set -euo pipefail
          mkdir -p eth_scalp_trader_pack_v0_1/data

          # ETHUSDT 1분봉 csv 자동 탐색 (여러 이름 변형 대응)
          CSV_PATH="$(find unzipped -type f -iname 'ETHUSDT*1*min*.csv' -o -iname 'ETH*USDT*1m*.csv' -o -iname 'ETHUSDT_1min_*.csv' | head -n1 || true)"
          if [ -z "${CSV_PATH:-}" ]; then
            echo "::error::unzipped/* 에서 ETHUSDT 1분봉 CSV를 찾지 못했습니다. zip 내부 파일명을 확인하세요."
            echo "unzipped 트리:"
            find unzipped -maxdepth 3 -print
            exit 3
          fi

          echo "Found CSV: $CSV_PATH"
          cp "$CSV_PATH" eth_scalp_trader_pack_v0_1/data/ETHUSDT-1m.csv
          ls -l eth_scalp_trader_pack_v0_1/data

      - name: Verify required files exist
        run: |
          set -euo pipefail
          test -f eth_scalp_trader_pack_v0_1/requirements.txt
          test -f eth_scalp_trader_pack_v0_1/config.yml
          test -f eth_scalp_trader_pack_v0_1/run_backtest.py
          test -f eth_scalp_trader_pack_v0_1/data/ETHUSDT-1m.csv
          echo "✅ inputs ready"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r eth_scalp_trader_pack_v0_1/requirements.txt

      - name: Run backtest
        working-directory: eth_scalp_trader_pack_v0_1
        env:
          PYTHONUNBUFFERED: "1"
        run: |
          set -euo pipefail
          python run_backtest.py --config config.yml
          echo "== outputs =="
          ls -la
          echo "== results (if any) =="
          find . -maxdepth 2 -type f \( -name 'equity*.csv' -o -name 'metrics*.json' \) -print || true
          echo "== logs =="
          if [ -d logs ]; then ls -la logs; fi

      - name: Upload artifacts (pinned)
        if: always()
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4.6.2
        with:
          name: scalper-backtest-${{ github.run_id }}
          if-no-files-found: warn
          path: |
            eth_scalp_trader_pack_v0_1/**/equity*.csv
            eth_scalp_trader_pack_v0_1/**/metrics*.json
            eth_scalp_trader_pack_v0_1/logs/**
