name: Single Sensitivity 3x3 - safe

on:
  workflow_dispatch:

env:
  PY_VERSION: "3.10"
  BASE_PARAMS: "conf/params_alt.yml"
  BASE_THR: "0.83"
  BASE_HOLD: "9"
  CSV_GLOB: "**/*ETHUSDT*1min*2020*2025*.csv"
  DATA_ZIP: "ETHUSDT_1min_2020_2025.zip"

jobs:
  sweep:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (pinned)
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Setup Python (pinned)
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: ${{ env.PY_VERSION }}

      - name: Deps (numba pinned)
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip wheel setuptools
          pip install "numpy==1.26.4" "pandas==2.2.2" "pyyaml" "numba==0.59.1" "llvmlite==0.42.0"

      - name: Unzip data if present
        run: |
          set -euo pipefail
          if [ -f "${DATA_ZIP}" ]; then unzip -o "${DATA_ZIP}" >/dev/null; fi

      - name: Normalize CSV_GLOB (strip repo & 'Multiregime 4t*')
        run: |
          set -euo pipefail
          ROOTF="$(basename "$GITHUB_WORKSPACE")"
          CSVG_IN="${CSV_GLOB}"
          CSVG="${CSVG_IN#${ROOTF}/}"; CSVG="${CSVG#./}"
          CSVG="$(printf '%s' "$CSVG" | sed -E 's#^(Multiregime[ _]4t[^/]*/)+##')"
          echo "CSVG_SANITIZED=$CSVG" >> "$GITHUB_ENV"
          echo "[glob] $CSVG"

      - name: Build THR/HOLD lists
        run: |
          THR1=$(python -c "import os;print(f'{float(os.environ.get(\"BASE_THR\",\"0.83\"))-0.02:.2f}')")
          THR2=$(python -c "import os;print(f'{float(os.environ.get(\"BASE_THR\",\"0.83\")):.2f}')")
          THR3=$(python -c "import os;print(f'{float(os.environ.get(\"BASE_THR\",\"0.83\"))+0.02:.2f}')")
          echo "THR_LIST=$THR1 $THR2 $THR3" >> $GITHUB_ENV
          H=$(python -c "import os;print(int(os.environ.get('BASE_HOLD','9')))"); echo "HOLD_LIST=$((H-1)) $H $((H+1))" >> $GITHUB_ENV

      - name: Run sweep and bundle
        env:
          THR_LIST: ${{ env.THR_LIST }}
          HOLD_LIST: ${{ env.HOLD_LIST }}
        run: |
          set -euo pipefail
          for THR in $THR_LIST; do
            for HOLD in $HOLD_LIST; do
              OUT="out_thr${THR}_h${HOLD}"
              python ci/wfo_entry.py \
                --params "${BASE_PARAMS}" \
                --data-root "." \
                --csv-glob "$CSVG_SANITIZED" \
                --outdir "$OUT" \
                --thr "$THR" \
                --hold "$HOLD" || true
              ( cd "$OUT" && zip -rq ../sweep_${THR}_${HOLD}.zip . ) || true
            done
          done
          AGG="sweep_3x3_bundle_${GITHUB_SHA::7}.zip"
          zip -rq "$AGG" sweep_*.zip
          mkdir -p _agg && mv "$AGG" _agg/

      - name: Upload aggregated artifact (pinned)
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: sweep_3x3_bundle
          path: _agg/sweep_3x3_bundle_*.zip