name: Single Sensitivity VECTORIZED - enforce metrics

on:
  workflow_dispatch:

env:
  PY_VERSION: "3.10"
  BASE_PARAMS: "conf/params_alt.yml"   # 또는 conf/params_champion.yml
  THR_LIST: "0.81 0.83 0.85"
  HOLD_LIST: "8 9 10"
  CSV_GLOB: "**/*ETHUSDT*1min*2020*2025*.csv"
  DATA_ZIP: "ETHUSDT_1min_2020_2025.zip"

jobs:
  vec:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (pinned)
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
      - name: Setup Python (pinned)
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: ${{ env.PY_VERSION }}

      - name: Deps (numba pinned)
        run: |
          set -euo pipefail
          python -m pip install --upgrade pip wheel setuptools
          pip install "numpy==1.26.4" "pandas==2.2.2" "pyyaml" "numba==0.59.1" "llvmlite==0.42.0"

      - name: Unzip data if present
        run: |
          set -euo pipefail
          if [ -f "${DATA_ZIP}" ]; then unzip -o "${DATA_ZIP}" >/dev/null; fi

      - name: Normalize CSV_GLOB (strip repo & 'Multiregime 4t*')
        run: |
          set -euo pipefail
          ROOTF="$(basename "$GITHUB_WORKSPACE")"
          CSVG="${CSV_GLOB#${ROOTF}/}"; CSVG="${CSVG#./}"
          CSVG="$(printf '%s' "$CSVG" | sed -E 's#^(Multiregime[ _]4t[^/]*/)+##')"
          echo "CSVG_SANITIZED=$CSVG" >> "$GITHUB_ENV"
          echo "[glob] $CSVG"

      - name: Run vectorized sensitivity
        run: |
          set -euo pipefail
          python ci/sensitivity_vec.py \
            --params "${BASE_PARAMS}" \
            --data-root "." \
            --csv-glob "$CSVG_SANITIZED" \
            --thr-list ${THR_LIST} \
            --hold-list ${HOLD_LIST} \
            --codepack "strategy_v2_codepack_v2.1.3.zip" \
            --out-bundle "sweep_vec_bundle_${GITHUB_SHA::7}.zip"

      - name: Enforce metrics for each cell & rebuild bundle
        env:
          THR_LIST: ${{ env.THR_LIST }}
          HOLD_LIST: ${{ env.HOLD_LIST }}
        run: |
          set -euo pipefail
          for THR in $THR_LIST; do
            for HOLD in $HOLD_LIST; do
              OUT="out_thr${THR}_h${HOLD}"
              python ci/precheck_contract.py --data-root "." --csv-glob "$CSVG_SANITIZED" --outdir "$OUT" || true
              python ci/metrics_enforcer.py \
                --outdir "$OUT" \
                --data-root "." \
                --csv-glob "$CSVG_SANITIZED" \
                --thr "${THR}" \
                --hold "${HOLD}"
              ( cd "$OUT" && zip -rq ../sweep_${THR}_${HOLD}.zip . )
            done
          done
          zip -rq "sweep_vec_bundle_enforced_${GITHUB_SHA::7}.zip" sweep_*.zip
          mkdir -p _agg && mv "sweep_vec_bundle_enforced_${GITHUB_SHA::7}.zip" _agg/

      - name: Upload aggregated artifact (pinned)
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: sweep_vec_bundle
          path: _agg/sweep_vec_bundle_enforced_*.zip
