name: Smoke119L

on:
  workflow_dispatch:
    inputs:
      CODE_ZIP:   { description: 'code zip at repo root', required: true, default: trade_v1.1.9.3.zip }
      DATA_ZIP:   { description: 'data zip at repo root', required: true, default: ETHUSDT_1min_2020_2025.zip }
      CSV_FILE:   { description: 'csv filename after unzip', required: true, default: ETHUSDT_1min_2020_2025.csv }
      TP:         { description: 'tp pct', required: true, default: "0.0035" }
      SL:         { description: 'sl pct', required: true, default: "0.0018" }
      HOLD:       { description: 'hold bars', required: true, default: "6" }
      THR_US:     { description: 'z-thr US', required: true, default: "4.0" }
      THR_EU:     { description: 'z-thr EU', required: true, default: "3.8" }
      THR_ASIA:   { description: 'z-thr ASIA', required: true, default: "3.5" }
      MIN_GAP:    { description: 'min_gap_bars', required: true, default: "5" }
      STRICT_GUARD: { description: 'true=fail on flags; false=warn only', required: true, default: "false" }

jobs:
  smoke:
    runs-on: ubuntu-latest
    env:
      RUN_DIR: tmp/trade
      DATA_DIR: tmp/data
      OUT_DIR: _out_119/smoke
      PYVER: '3.11'

    steps:
      - name: Checkout (pinned)
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8
        with:
          fetch-depth: 0

      - name: Setup Python (pinned)
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065
        with:
          python-version: ${{ env.PYVER }}

      - name: Resolve ZIPs
        shell: bash
        run: |
          set -euo pipefail
          res(){ local in="$1" out="$2" p=""; local base="$(basename "$in")";
            if [[ -f "$in" ]] ; then p="${GITHUB_WORKSPACE}/$in";
            else p="$(find "${GITHUB_WORKSPACE}" -maxdepth 2 -type f -name "$base" -print -quit || true)"; fi
            [[ -n "$p" && -f "$p" ]] || { echo "::error::ZIP not found: $in"; exit 66; }
            echo "${out}=${p}" >> "$GITHUB_ENV"; echo "[resolved] $in -> $p";
          }
          res "${{ github.event.inputs.CODE_ZIP }}" CODE_ZIP_ABS
          res "${{ github.event.inputs.DATA_ZIP }}" DATA_ZIP_ABS

      - name: Unpack code/data & locate runner
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$RUN_DIR" "$DATA_DIR" "${GITHUB_WORKSPACE}/${OUT_DIR}"
          unzip -q "$CODE_ZIP_ABS" -d "$RUN_DIR"
          unzip -q "$DATA_ZIP_ABS" -d "$DATA_DIR"
          RUN_PY="$(find "$RUN_DIR" -maxdepth 4 -type f -name 'run_4u.py' -print -quit || true)"
          [[ -n "$RUN_PY" ]] || { echo "::error::run_4u.py not found in code zip"; exit 67; }
          echo "RUN_PY=$RUN_PY" >> "$GITHUB_ENV"
          echo "OUT_DIR_ABS=${GITHUB_WORKSPACE}/${OUT_DIR}" >> "$GITHUB_ENV"

      - name: CSV preflight (required columns + n_rows)
        shell: bash
        run: |
          set -euo pipefail
          CSV="${GITHUB_WORKSPACE}/${DATA_DIR}/${{ github.event.inputs.CSV_FILE }}"
          if [[ ! -f "$CSV" ]]; then
            F="$(find "$DATA_DIR" -type f -name '${{ github.event.inputs.CSV_FILE }}' -print -quit || true)"
            [[ -n "$F" ]] || { echo "::error::CSV not found: ${{ github.event.inputs.CSV_FILE }}"; exit 64; }
            CSV="${GITHUB_WORKSPACE}/${F}"
          fi
          echo "CSV_PATH=$CSV" >> "$GITHUB_ENV"
          HDR="$(head -n1 "$CSV")"
          for c in open_time open high low close volume; do
            echo "$HDR" | grep -q "\b$c\b" || { echo "::error::missing column: $c"; exit 75; }
          done
          NROWS=$(($(wc -l < "$CSV") - 1))
          echo "N_ROWS=$NROWS" >> "$GITHUB_ENV"
          jq -n --arg path "$CSV" --arg hdr "$HDR" --argjson rows "$NROWS" '{path:$path, header:$hdr, n_rows:$rows}' \
            > "${GITHUB_WORKSPACE}/${OUT_DIR}/preflight.json"

      - name: Write conf.effective.yml (printf only)
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p "$RUN_DIR/conf"
          CONF="$RUN_DIR/conf/config.effective.yml"
          : > "$CONF"
          printf '%s\n' 'thr_by_session:'                         >> "$CONF"
          printf '%s\n' "  US: ${{ github.event.inputs.THR_US }}"    >> "$CONF"
          printf '%s\n' "  EU: ${{ github.event.inputs.THR_EU }}"    >> "$CONF"
          printf '%s\n' "  ASIA: ${{ github.event.inputs.THR_ASIA }}" >> "$CONF"
          printf '%s\n' "tp_pct: ${{ github.event.inputs.TP }}"      >> "$CONF"
          printf '%s\n' "sl_pct: ${{ github.event.inputs.SL }}"      >> "$CONF"
          printf '%s\n' "hold_bars: ${{ github.event.inputs.HOLD }}" >> "$CONF"
          printf '%s\n' "z_window: 288"                              >> "$CONF"
          printf '%s\n' "long_only: true"                            >> "$CONF"
          printf '%s\n' "pred_pos_means_long: false"                 >> "$CONF"
          printf '%s\n' "mcc_mode: trade_vs_not"                     >> "$CONF"
          printf '%s\n' "mcc_sample: all_bars"                       >> "$CONF"
          printf '%s\n' "xor_tp_sl: true"                            >> "$CONF"
          printf '%s\n' "min_gap_bars: ${{ github.event.inputs.MIN_GAP }}" >> "$CONF"
          printf '%s\n' "fees_roundtrip: 0.0004"                     >> "$CONF"
          sha256sum "$CONF" | awk '{print "[conf] sha256="$1}'

      - name: Install deps
        shell: bash
        run: |
          set -euo pipefail
          python -m pip install -U pip >/dev/null
          pip install pandas numpy pyyaml >/dev/null
          if ! command -v jq >/dev/null 2>&1; then sudo apt-get update -y && sudo apt-get install -y jq; fi

      - name: Run engine
        shell: bash
        run: |
          set -euo pipefail
          export PYTHONPATH="$RUN_DIR"
          python "$RUN_PY" --data_path "$CSV_PATH" --out_dir "${OUT_DIR_ABS}"
          # show error if exists
          if [[ -f "${OUT_DIR_ABS}/error.json" ]]; then echo "== error.json =="; cat "${OUT_DIR_ABS}/error.json"; fi

      - name: Write diag_post.py (printf; no heredoc)
        shell: bash
        run: |
          set -euo pipefail
          D="${GITHUB_WORKSPACE}/diag_post.py"; : > "$D"
          printf '%s\n' "import os, json, math, pandas as pd, numpy as np, pathlib" >> "$D"
          printf '%s\n' "out = pathlib.Path(os.environ['GITHUB_WORKSPACE'])/os.environ['OUT_DIR']" >> "$D"
          printf '%s\n' "s = json.loads((out/'summary.json').read_text())" >> "$D"
          printf '%s\n' "pre = json.loads((out/'preflight.json').read_text()) if (out/'preflight.json').exists() else {}" >> "$D"
          printf '%s\n' "rows = pre.get('n_rows') or s.get('n_rows')" >> "$D"
          printf '%s\n' "df = pd.read_csv(out/'trades.csv')" >> "$D"
          printf '%s\n' "pnl = df['PnL'].astype(float).values if 'PnL' in df.columns else None" >> "$D"
          printf '%s\n' "pos = pnl[pnl>0].sum(); neg = -pnl[pnl<0].sum() if pnl is not None else (0,0)" >> "$D"
          printf '%s\n' "pf_t = (pos/neg) if neg>0 else None" >> "$D"
          printf '%s\n' "hit_t = float((pnl>0).mean()) if pnl is not None and pnl.size>0 else None" >> "$D"
          printf '%s\n' "ratio = (s.get('n_trades')/rows) if rows else None" >> "$D"
          printf '%s\n' "flags=[]" >> "$D"
          printf '%s\n' "if ratio is not None and ratio>0.45: flags.append('DENSE_RUN')" >> "$D"
          printf '%s\n' "if s.get('mcc') is not None and s.get('hit_rate') is not None and s['mcc']>0.7 and s['hit_rate']<0.45: flags.append('SIGN_MAPPING_SUSPECT')" >> "$D"
          printf '%s\n' "diag={'n_rows':rows,'n_trades':s.get('n_trades'),'ratio':ratio,'hit_rate':s.get('hit_rate'),'pf':s.get('profit_factor'),'mcc':s.get('mcc'),'flags':flags}" >> "$D"
          printf '%s\n' "(out/'diag.json').write_text(json.dumps(diag, indent=2))" >> "$D"
          printf '%s\n' "print(json.dumps(diag, indent=2))" >> "$D"

      - name: Run diagnostics & (soft) gate
        shell: bash
        run: |
          set -euo pipefail
          python "${GITHUB_WORKSPACE}/diag_post.py" | tee /tmp/diag.json
          FLAGS="$(jq -r '.flags|join(",")' "${{ github.workspace }}/${{ env.OUT_DIR }}/diag.json")"
          echo "[flags] ${FLAGS}"
          if [[ "${{ github.event.inputs.STRICT_GUARD }}" == "true" && -n "$FLAGS" ]]; then exit 79; fi

      - name: Upload smoke outputs (pinned)
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: smoke119l_out
          path: |
            ${{ env.OUT_DIR }}/summary.json
            ${{ env.OUT_DIR }}/trades.csv
            ${{ env.OUT_DIR }}/gating_debug.json
            ${{ env.OUT_DIR }}/preflight.json
            ${{ env.OUT_DIR }}/diag.json